import { describe, it, expect } from 'vitest';
import { sha256JS, generateSha256Input } from './sha256';

// Helper to convert Uint8Array to hex for easier visual comparison
function toHex(buffer: Uint8Array): string {
  return Array.from(buffer)
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

describe('sha256JS', () => {
  it('computes correct SHA-256 for an empty message', () => {
    const input = new Uint8Array(0);
    const digest = sha256JS(input);
    expect(toHex(digest)).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
  });

  it('computes correct SHA-256 for "abc"', () => {
    const input = new TextEncoder().encode('abc');
    const digest = sha256JS(input);
    expect(toHex(digest)).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
  });

  it('computes correct SHA-256 for a longer standard test vector', () => {
    const input = new TextEncoder().encode('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq');
    const digest = sha256JS(input);
    expect(toHex(digest)).toBe('248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1');
  });

  it('computes deterministically generated inputs', () => {
    const input = generateSha256Input(100);
    expect(input.length).toBe(100);
    const digest = sha256JS(input);
    expect(digest.length).toBe(32);
    expect(toHex(digest).length).toBe(64);
  });

  describe('padding-boundary test matrix', () => {
    // Expected values are pre-computed independently (e.g. via Node.js crypto module)
    // for the precise byte sequence generated by `generateSha256Input`.
    const expectedHashes: Record<number, string> = {
      55: '166cb1ce48dba01b7d55341ae1d847d73f24f538ecf4911f657fba255b83d2aa',
      56: '1bfb069cb406b899a507a8a00c5d721c207463d63e313b6dd994ce67cb46cc13',
      57: '81c44c9ad65412972b63fcab88e0b3b3ba8dadc4fc533525f6698f458a8ad6c3',
      63: 'f7191804fb70f054952e831548291633b7a1f300f0f4d877f38d995ed4ce274b',
      64: '2d91cac9246ea9f11939b47308360f0c8e8be87db686dc3c1d1dcbf91eb054cf',
      65: 'd0c7d32839006da594139cfa302b1e478c238355573c80079aa4be0a94621c56',
      127: 'f6a779f356943adb60fffef004625272ae8e1421cce45d5a02d142a8f6229031',
      128: '477f9dbe9ced58a04330559b8e5a755753f3d72680062f2d72fe57e4b9370df1',
      129: '07780ed5a9c7be22ecc1ce1ba1e5432a7b8bfd61a2f43d67cd06622d96e0e90e',
    };

    for (const [lenStr, expected] of Object.entries(expectedHashes)) {
      const len = parseInt(lenStr, 10);
      it(`computes correct SHA-256 for deterministic input of length ${len}`, () => {
        const input = generateSha256Input(len);
        const digest = sha256JS(input);
        expect(digest.length).toBe(32);
        expect(toHex(digest)).toBe(expected);
      });
    }
  });
});
